### PR TITLE
removed Natives and audio stuff from JDA

### PR DESCRIPTION
**Pull request by James137137**
This is so it is approvable by bukkit and removing un-needed classes/files

### CODE REVIEW

**Comment by James137137** [comment]
see https://github.com/James137137/JDA/commits/master for changes made to JDA

**Comment by James137137** [comment]
also @LXGaming make sure you test it out first

**Comment by LXGaming** [comment]
Thank you for alerting me to the Natives issue.

Due to you modifying the JDA Source code, this pull request will be close and not merged. The reason for this is merging future JDA updates might cause unexpected issues with the API during use and/or conflicts with merging.

I have gone ahead and forked JDA (https://github.com/LXGaming/JDA) and have altered the project to allow building via Maven, during build its set not to compile dependencies and resource files that are related to the audio side of JDA. In this instance the source code of JDA has not been touched.

Again Thank you James for alerting me to the Natives files being compiled by JDA, and for creating this pull request to help out. :)

**Comment by James137137** [comment]
yeah. I think just removing the "resource files that are related to the audio side of JDA."  is a the main point.

no problem. Always glad to help

**Pull request closed without merging**
